name: simple_moment
description: A simple implementation of the Moment.js features for relative time.
version: 1.0.5
homepage: https://github.com/rinukkusu/simple_moment

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: ^0.16.1

dev_dependencies:
  test: ^1.3.0
